version: '3.8'

services:
  db:
    container_name: spring_mocks_pg
    hostname: db
    image: postgres:14.2
    restart: unless-stopped
    ports:
      - 6001:5432
    environment:
      POSTGRES_PASSWORD: spring_mocks_pg
    networks:
      - spring_mocks

networks:
  spring_mocks:
    name: spring_mocks
    driver: bridge
