version: '3.8'

services:
  db:
    container_name: spring_mocks_pg
    hostname: db
    image: postgres:14.2
    restart: always
    ports:
      - 6001:5432
    environment:
      POSTGRES_PASSWORD: spring_mocks_pg
    networks:
      - spring_mocks_prod
  web:
    container_name: spring_mocks_web
    image: downvoteit/spring-mocks:0.0.1-SNAPSHOT
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx128m -Dspring.profiles.active=prod"
      JDBC_URL: jdbc:postgresql://db:5432/postgres
      JDBC_USER: postgres
      JDBC_PASSWORD: spring_mocks_pg
      JDBC_SCHEMA: postgres
      SERVER_PORT: ${SERVER_PORT}
    networks:
      - spring_mocks_prod
    depends_on:
      - db

networks:
  spring_mocks_prod:
    driver: bridge

