version: '3.1'

services:
  db:
    container_name: spring_mocks_pg
    image: postgres:14.2
    restart: always
    ports:
      - 6001:5432
    environment:
      POSTGRES_PASSWORD: spring_mocks_pg
networks:
  default:
    name: spring_mocks_default
