spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: select 1
      auto-commit: true
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
  h2:
    console:
      enabled: true
      path: /console
server:
  port: 6002
