spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: select 1
      auto-commit: true
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
  h2:
    console:
      enabled: true
      path: /console
  flyway:
    enabled: false
server:
  port: 6002
