spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:6001/postgres
    username: postgres
    password: spring_mocks_pg
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
      auto-commit: true
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  flyway:
    enabled: true
    locations: classpath:db/versions
    url: jdbc:postgresql://localhost:6001/postgres
    schemas: postgres
    user: postgres
    password: spring_mocks_pg
server:
  port: 6002
