spring:
  main:
    banner-mode: off
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
      auto-commit: true
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  flyway:
    enabled: true
    locations: classpath:db/versions
    url: ${JDBC_URL}
    user: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    schemas: ${JDBC_SCHEMA}
server:
  port: ${SERVER_PORT}
