spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:6001/postgres
    username: postgres
    password: spring_mocks_pg
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
      auto-commit: true
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
server:
  port: 6002
